
set(FreeRTOS_INCLUDE_PUBLIC_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")

file(GLOB FreeRTOS_SOURCES_CORE "${CMAKE_CURRENT_LIST_DIR}/*.c")
file(GLOB_RECURSE FreeRTOS_SOURCES_LIBS
        "${CMAKE_CURRENT_LIST_DIR}/lib*/*.c"
        "${CMAKE_CURRENT_LIST_DIR}/portable/*.c"
        "${CMAKE_CURRENT_LIST_DIR}/MemMang/heap_4.c")

set(FreeRTOS_SOURCES ${FreeRTOS_SOURCES_CORE} ${FreeRTOS_SOURCES_LIBS})